### use balance 1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### use balance 2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "5c7993281dfe46f7b59af170d709c634",
  "accountNumber": "1000000000",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/a9c85dbcfdee4b7f916955f6371ed32e
Accept: application/json